// ai_questions.dart
// This file contains hard-coded AI prompt questions for all 51 AS9102 fields

const String questionEnding = 'Please paraphrase what information is required, what is considered acceptable, and what common mistakes to avoid. Do not quote or copy the official AS9102 text. Explain in your own words for educational clarity.';
const String questionEndingNoAS9102 = 'Please paraphrase what information is required, what is considered acceptable, and what common mistakes to avoid. Do not quote or copy, copy written text. Explain in your own words for educational clarity.';
const Map<String, String> aiQuestions = {

  'Form1_Field1': 'Regarding AS9102 Rev. C: Form 1 / Field 1 — Part Number: $questionEnding',
  'Form1_Field2': 'Regarding AS9102 Rev. C: Form 1 / Field 2 — Part Name: $questionEnding',
  'Form1_Field3': 'Regarding AS9102 Rev. C: Form 1 / Field 3 — Serial Number: $questionEnding',
  'Form1_Field4': 'Regarding AS9102 Rev. C: Form 1 / Field 4 — FAIR Identifier: $questionEnding',
  'Form1_Field5': 'Regarding AS9102 Rev. C: Form 1 / Field 5 — Part Revision Level: $questionEnding',
  'Form1_Field6': 'Regarding AS9102 Rev. C: Form 1 / Field 6 — Drawing Number: $questionEnding',
  'Form1_Field7': 'Regarding AS9102 Rev. C: Form 1 / Field 7 — Drawing Revision Level: $questionEnding',
  'Form1_Field8': 'Regarding AS9102 Rev. C: Form 1 / Field 8 — Additional Changes: $questionEnding',
  'Form1_Field9': 'Regarding AS9102 Rev. C: Form 1 / Field 9 — Manufacturing Process Reference: $questionEnding',
  'Form1_Field10': 'Regarding AS9102 Rev. C: Form 1 / Field 10 — Organization Name: $questionEnding',
  'Form1_Field11': 'Regarding AS9102 Rev. C: Form 1 / Field 11 — Supplier Code: $questionEnding',
  'Form1_Field12': 'Regarding AS9102 Rev. C: Form 1 / Field 12 — Purchase Order Number: $questionEnding',
  'Form1_Field13': 'Regarding AS9102 Rev. C: Form 1 / Field 13 — Detail or Assembly: $questionEnding',
  'Form1_Field14': 'Regarding AS9102 Rev. C: Form 1 / Field 14 — Full or Partial FAI: $questionEnding',
  'Form1_Field15': 'Regarding AS9102 Rev. C: Form 1 / Field 15 — Part Number Index, Part Number: $questionEnding',
  'Form1_Field16': 'Regarding AS9102 Rev. C: Form 1 / Field 16 — Part Number Index, Part Name: $questionEnding',
  'Form1_Field17': 'Regarding AS9102 Rev. C: Form 1 / Field 17 — Part Number Index, Part Type: $questionEnding',
  'Form1_Field18': 'Regarding AS9102 Rev. C: Form 1 / Field 18 — Part Number Index, FAIR Identifier $questionEnding',
  'Form1_Field19': 'Regarding AS9102 Rev. C: Form 1 / Field 19 — Does FAIR contain a documented Nonconformance $questionEnding',
  'Form1_Field20': 'Regarding AS9102 Rev. C: Form 1 / Field 20 — FAIR Reviewed by $questionEnding',
  'Form1_Field21': 'Regarding AS9102 Rev. C: Form 1 / Field 21 — Date when field 20 was populated $questionEnding',
  'Form1_Field22': 'Regarding AS9102 Rev. C: Form 1 / Field 22 — FAIR reviewed/approved by $questionEnding',
  'Form1_Field23': 'Regarding AS9102 Rev. C: Form 1 / Field 23 — Date when field 22 was populated $questionEnding',
  'Form1_Field24': 'Regarding AS9102 Rev. C: Form 1 / Field 24 — Customer Approval $questionEnding',
  'Form1_Field25': 'Regarding AS9102 Rev. C: Form 1 / Field 25 — Date when field 24 was populated $questionEnding',
  'Form1_Field26': 'Regarding AS9102 Rev. C: Form 1 / Field 26 — Comments $questionEnding',
  'Form2_Field1': 'Regarding AS9102 Rev. C: Form 2 / Field 1 — Part Number $questionEnding',
  'Form2_Field2': 'Regarding AS9102 Rev. C: Form 2 / Field 2 — Part Name $questionEnding',
  'Form2_Field3': 'Regarding AS9102 Rev. C: Form 2 / Field 3 — Serial Number $questionEnding',
  'Form2_Field4': 'Regarding AS9102 Rev. C: Form 2 / Field 4 — FAIR Identifier $questionEnding',
  'Form2_Field5': 'Regarding AS9102 Rev. C: Form 2 / Field 5 — Material or Process Name $questionEnding',
  'Form2_Field6': 'Regarding AS9102 Rev. C: Form 2 / Field 6 — Material or Process Specification Number $questionEnding',
  'Form2_Field7': 'Regarding AS9102 Rev. C: Form 2 / Field 7 — Material or Process Code $questionEnding',
  'Form2_Field8': 'Regarding AS9102 Rev. C: Form 2 / Field 8 — Material or Process Supplier $questionEnding',
  'Form2_Field9': 'Regarding AS9102 Rev. C: Form 2 / Field 9 — Material or Process Customer Approval Verification $questionEnding',
  'Form2_Field10': 'Regarding AS9102 Rev. C: Form 2 / Field 10 — Material or Process Certificate of Conformance Number $questionEnding',
  'Form2_Field11': 'Regarding AS9102 Rev. C: Form 2 / Field 11 — Functional Test Procedure Number $questionEnding',
  'Form2_Field12': 'Regarding AS9102 Rev. C: Form 2 / Field 12 — Acceptance Report Number $questionEnding',
  'Form2_Field13': 'Regarding AS9102 Rev. C: Form 2 / Field 13 — Comments $questionEnding',
  'Form3_Field1': 'Regarding AS9102 Rev. C: Form 3 / Field 1 — Part Number $questionEnding',
  'Form3_Field2': 'Regarding AS9102 Rev. C: Form 3 / Field 2 — Part Name $questionEnding',
  'Form3_Field3': 'Regarding AS9102 Rev. C: Form 3 / Field 3 — Serial Number $questionEnding',
  'Form3_Field4': 'Regarding AS9102 Rev. C: Form 3 / Field 4 — FAIR Identifier $questionEnding',
  'Form3_Field5': 'Regarding AS9102 Rev. C: Form 3 / Field 5 — Char. No. $questionEnding',
  'Form3_Field6': 'Regarding AS9102 Rev. C: Form 3 / Field 6 — Reference Location $questionEnding',
  'Form3_Field7': 'Regarding AS9102 Rev. C: Form 3 / Field 7 — Characteristic Designator $questionEnding',
  'Form3_Field8': 'Regarding AS9102 Rev. C: Form 3 / Field 8 — Requirements $questionEnding',
  'Form3_Field9': 'Regarding AS9102 Rev. C: Form 3 / Field 9 — Results $questionEnding',
  'Form3_Field10': 'Regarding AS9102 Rev. C: Form 3 / Field 10 — Designed/Qualified Tooling $questionEnding',
  'Form3_Field11': 'Regarding AS9102 Rev. C: Form 3 / Field 11 — Nonconformance Number $questionEnding',
  'Form3_Field12': 'Regarding AS9102 Rev. C: Form 3 / Field 12 — Additional Data/Comments $questionEnding',

// Next Questions are for the DOCUMENTS (DocumentListPage)

'documents_Field1': 'What should an FAI reviewer look for in a Purchase Order document? $questionEndingNoAS9102',
'documents_Field2': 'What should an FAI reviewer look for in a Drawing? $questionEndingNoAS9102',
'documents_Field3': 'What should an FAI reviewer look for in a Parts List? $questionEndingNoAS9102',
'documents_Field4': 'What should an FAI reviewer look for in AS9102 FAI forms 1, 2, and 3? $questionEndingNoAS9102',
'documents_Field5': 'What should an FAI reviewer look for in a Packing list document? $questionEndingNoAS9102',
'documents_Field6': 'What should an FAI reviewer look for in a specification? $questionEndingNoAS9102',
'documents_Field7': 'What should an FAI reviewer look for in a work order, traveler, or router? $questionEndingNoAS9102',
'documents_Field8': 'What should an FAI reviewer look for in part photos? $questionEndingNoAS9102',
'documents_Field9': 'What should an FAI reviewer look for in hole plugging photos? $questionEndingNoAS9102',
'documents_Field10': 'What should an FAI reviewer look for in part marking photos? $questionEndingNoAS9102',
'documents_Field11': 'What should an FAI reviewer look for in processing photos? $questionEndingNoAS9102',
'documents_Field12': 'How should an FAI reviewer write a review on a first article part? $questionEndingNoAS9102',

'certifications_Field1': 'What should an FAI reviewer look for in a material certification? $questionEndingNoAS9102',
'certifications_Field2': 'What should an FAI reviewer look for in a process certification? $questionEndingNoAS9102',
'certifications_Field3': 'What should an FAI reviewer look for in an ink certification? $questionEndingNoAS9102',
'certifications_Field4': 'What should an FAI reviewer look for in a fastener certification ? $questionEndingNoAS9102',
'certifications_Field5': 'What should an FAI reviewer look for in paint and primer certifications? $questionEndingNoAS9102',
'certifications_Field6': 'What should an FAI reviewer look for in Coating certifications? $questionEndingNoAS9102',
'certifications_Field7': 'What should an FAI reviewer look for in heat treat certifications? $questionEndingNoAS9102',
'certifications_Field8': 'What should an FAI reviewer look for in hardness and conductivity certifications? $questionEndingNoAS9102',
'certifications_Field9': 'What should an FAI reviewer look for in surface treatment certifications? $questionEndingNoAS9102',
'certifications_Field10': 'What should an FAI reviewer look for in test certifications? $questionEndingNoAS9102',
'certifications_Field11': 'What should an FAI reviewer look for in plating certifications? $questionEndingNoAS9102',
'certifications_Field12': 'What should an FAI reviewer hole plugging certifications? $questionEndingNoAS9102',
'certifications_Field13': 'What should an FAI reviewer look for in epoxy and bonding certifications? $questionEndingNoAS9102',
};